import { createContext, useState } from "react";

const ItemContext = createContext();

const ItemProvider = ({ children }) => {
  const [items, setItems] = useState([
    {
      id: 0,
      img: "https://neal.fun/spend/images/big-mac.jpg",
      name: "Big Mac",
      price: 2,
      amount: 0,
    },
    {
      id: 1,
      img: "https://neal.fun/spend/images/flip-flops.jpg",
      name: "Flip Flop",
      price: 3,
      amount: 0,
    },
    {
      id: 2,
      img: "https://neal.fun/spend/images/coca-cola-pack.jpg",
      name: "Coca Cola Pack",
      price: 5,
      amount: 0,
    },
    {
      id: 3,
      img: "https://neal.fun/spend/images/movie-ticket.jpg",
      name: "Movie Ticket",
      price: 12,
      amount: 0,
    },
    {
      id: 4,
      img: "https://neal.fun/spend/images/book.jpg",
      name: "Book",
      price: 15,
      amount: 0,
    },
    {
      id: 5,
      img: "https://neal.fun/spend/images/lobster-dinner.jpg",
      name: "Lobster Dinner",
      price: 45,
      amount: 0,
    },
    {
      id: 6,
      img: "https://neal.fun/spend/images/video-game.jpg",
      name: "Video Game",
      price: 60,
      amount: 0,
    },
    {
      id: 7,
      img: "https://neal.fun/spend/images/amazon-echo.jpg",
      name: "Amazon Echo",
      price: 99,
      amount: 0,
    },
    {
      id: 8,
      img: "https://neal.fun/spend/images/year-of-netflix.jpg",
      name: "Year of Netflix",
      price: 100,
      amount: 0,
    },
    {
      id: 9,
      img: "https://neal.fun/spend/images/air-jordans.jpg",
      name: "Air Jordans",
      price: 125,
      amount: 0,
    },
    {
      id: 10,
      img: "https://neal.fun/spend/images/airpods.jpg",
      name: "Airpods",
      price: 199,
      amount: 0,
    },
    {
      id: 11,
      img: "https://neal.fun/spend/images/gaming-console.jpg",
      name: "Gaming Console",
      price: 299,
      amount: 0,
    },
    {
      id: 12,
      img: "https://neal.fun/spend/images/drone.jpg",
      name: "Drone",
      price: 350,
      amount: 0,
    },
    {
      id: 13,
      img: "https://neal.fun/spend/images/smartphone.jpg",
      name: "Smartphone",
      price: 699,
      amount: 0,
    },
    {
      id: 14,
      img: "https://neal.fun/spend/images/bike.jpg",
      name: "Bike",
      price: 800,
      amount: 0,
    },
    {
      id: 15,
      img: "https://neal.fun/spend/images/kitten.jpg",
      name: "Kitten",
      price: 1500,
      amount: 0,
    },
    {
      id: 16,
      img: "https://neal.fun/spend/images/puppy.jpg",
      name: "Puppy",
      price: 1500,
      amount: 0,
    },
    {
      id: 17,
      img: "https://neal.fun/spend/images/auto-rickshaw.jpg",
      name: "Auto Rickshaw",
      price: 2300,
      amount: 0,
    },
    {
      id: 18,
      img: "https://neal.fun/spend/images/horse.jpg",
      name: "Horse",
      price: 2500,
      amount: 0,
    },
    {
      id: 19,
      img: "https://neal.fun/spend/images/acre-of-farmland.jpg",
      name: "Acre of Farmland",
      price: 3000,
      amount: 0,
    },
    {
      id: 20,
      img: "https://neal.fun/spend/images/designer-handbag.jpg",
      name: "Designer Handbag",
      price: 5500,
      amount: 0,
    },
    {
      id: 21,
      img: "https://neal.fun/spend/images/hot-tub.jpg",
      name: "Hot Tub",
      price: 6000,
      amount: 0,
    },
    {
      id: 22,
      img: "https://neal.fun/spend/images/luxury-wine.jpg",
      name: "Luxury Wine",
      price: 7000,
      amount: 0,
    },
    {
      id: 23,
      img: "https://neal.fun/spend/images/diamond-ring.jpg",
      name: "Diamond Ring",
      price: 10000,
      amount: 0,
    },
    {
      id: 24,
      img: "https://neal.fun/spend/images/jet-ski.jpg",
      name: "Jet Ski",
      price: 12000,
      amount: 0,
    },
    {
      id: 25,
      img: "https://neal.fun/spend/images/rolex.jpg",
      name: "Rolex",
      price: 15000,
      amount: 0,
    },
    {
      id: 26,
      img: "https://neal.fun/spend/images/ford-f-150.jpg",
      name: "Ford F-150",
      price: 30000,
      amount: 0,
    },
    {
      id: 27,
      img: "https://neal.fun/spend/images/tesla.jpg",
      name: "Tesla",
      price: 75000,
      amount: 0,
    },
    {
      id: 28,
      img: "https://neal.fun/spend/images/monster-truck.jpg",
      name: "Monster Truck",
      price: 150000,
      amount: 0,
    },
    {
      id: 29,
      img: "https://neal.fun/spend/images/ferrari.jpg",
      name: "Ferrari",
      price: 250000,
      amount: 0,
    },
    {
      id: 30,
      img: "https://neal.fun/spend/images/single-family-home.jpg",
      name: "Single Family Home",
      price: 300000,
      amount: 0,
    },
    {
      id: 31,
      img: "https://neal.fun/spend/images/gold-bar.jpg",
      name: "Gold Bar",
      price: 700000,
      amount: 0,
    },
    {
      id: 32,
      img: "https://neal.fun/spend/images/mcdonalds-franchise.jpg",
      name: "McDonalds Franchise",
      price: 1500000,
      amount: 0,
    },
    {
      id: 33,
      img: "https://neal.fun/spend/images/superbowl-ad.jpg",
      name: "Superbowl Ad",
      price: 5250000,
      amount: 0,
    },
    {
      id: 34,
      img: "https://neal.fun/spend/images/yacht.jpg",
      name: "Yacht",
      price: 7500000,
      amount: 0,
    },
    {
      id: 35,
      img: "https://neal.fun/spend/images/m1-abrams.jpg",
      name: "M1 Abrams",
      price: 8000000,
      amount: 0,
    },
    {
      id: 36,
      img: "https://neal.fun/spend/images/formula-1-car.jpg",
      name: "Formula 1 Car",
      price: 15000000,
      amount: 0,
    },
    {
      id: 37,
      img: "https://neal.fun/spend/images/apache-helicopter.jpg",
      name: "Apache Helicopter",
      price: 31000000,
      amount: 0,
    },
    {
      id: 38,
      img: "https://neal.fun/spend/images/mansion.jpg",
      name: "Mansion",
      price: 45000000,
      amount: 0,
    },
    {
      id: 39,
      img: "https://neal.fun/spend/images/make-a-movie.jpg",
      name: "Make a Movie",
      price: 100000000,
      amount: 0,
    },
    {
      id: 40,
      img: "https://neal.fun/spend/images/boeing-747.jpg",
      name: "Boeing 747",
      price: 148000000,
      amount: 0,
    },
    {
      id: 41,
      img: "https://neal.fun/spend/images/mona-lisa.jpg",
      name: "Mona Lisa",
      price: 780000000,
      amount: 0,
    },
    {
      id: 42,
      img: "https://neal.fun/spend/images/skyscraper.jpg",
      name: "Skyscraper",
      price: 850000000,
      amount: 0,
    },
    {
      id: 43,
      img: "https://neal.fun/spend/images/cruise-ship.jpg",
      name: "Cruise Ship",
      price: 930000000,
      amount: 0,
    },
    {
      id: 44,
      img: "https://neal.fun/spend/images/nba-team.jpg",
      name: "NBA Team",
      price: 2120000000,
      amount: 0,
    },
  ]);

  return (
    <ItemContext.Provider value={{ items, setItems }}>
      {children}
    </ItemContext.Provider>
  );
};

export { ItemContext, ItemProvider };

// const updatedItems = items.map(item => ({ ...item, amount: 0 }));
// setItems(updatedItems);
